import { reactive } from 'vue';
import { type TreeNode } from '@/types';

const AllItemList = reactive<TreeNode[]>([{
    id:1,
    name:"深圳技术大学",
    open:"closed",///open 控制子元素是否展开
    status:true,
    children:[
        {
            id:2,
            name:"职能部门",
            open:"closed",
            status:false, ///status 控制自己是什么状态
            children:[
                {
                    id:3,
                    name:"后勤部",
                    open:"closed",
                    status:false,
                    children:[
                        {
                           id:4,
                           name:"深圳技术大学医院",
                           open:"",
                           status:false,
                           children:  null 
                        },
                        {
                            id:5,
                            name:"餐饮服务中心",
                            open:"",
                            status:false,
                            children:null
                        }
                    ]
                },
                {
                    id:6,
                    name:"学生部（党委学生工作部、党委武装部）",
                    open:"",
                    status:false,
                    children: null
                },
                {
                    id:7,
                    name:"党政办公室",
                    open:"closed",
                    status:false,
                    children:[
                        {
                            id:8,
                            name:"法治工作",
                            open:"",
                            status:false,
                            children:null
                        },
                        {
                            id:9,
                            name:"档案室",
                            open:"",
                            status:false,
                            children:null
                        },
                    ]
                },
                {
                    id:10,
                    name:"国际合作与交流部（港澳台工作办公室）",
                    open:"",
                    status:false,
                    children:null
                },
                {
                    id:11,
                    name:"教务部",
                    open:"closed",
                    status:false,
                    children:[
                        {
                            id:12,
                            name:"继续教育中心",
                            open:"",
                            status:false,
                            children:null
                        },
                        {
                            id:13,
                            name:"艺术中心",
                            open:"",
                            status:false,
                            children:null
                        },
                        {
                            id:14,
                            name:"招生办公室",
                            open:"",
                            status:false,
                            children:null
                        },
                        {
                            id:15,
                            name:"交叉学科创新中心",
                            open:"",
                            status:false,
                            children:null
                        }
                    ]
                },
                {
                    id:16,
                    name:"国有资产与实验室管理开发部",
                    open:"closed",
                    status:false,
                    children:[
                        {
                            id:17,
                            name:"深圳市深技大资产运营管理有限公司",
                            open:"",
                            status:false,
                            children:null
                        },
                        {
                            id:18,
                            name:"分析测试中心",
                            open:"",
                            status:false,
                            children:null
                        }
                    ]
                },
                {
                    id:19,
                    name:"发展规划部",
                    open:"",
                    status:false,
                    children:null
                },
                {
                    id:20,
                    name:"审计室",
                    open:"",
                    status:false,
                    children:null
                },
                {
                    id:21,
                    name:"计划财务部",
                    open:"",
                    status:false,
                    children:null
                },
                {
                    id:22,
                    name:"党委宣传部",
                    open:"",
                    status:false,
                    children:null
                },
                {
                    id:23,
                    name:"科研与校企合作部",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:24,
                    name:"人力资源部（党委教师工作部）",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:25,
                    name:"党委组织部（党委统战部）",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:26,
                    name:"纪检监察室",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:27,
                    name:"安全保卫中心",
                    open:"",
                    status:false,
                    children:null,
                }
            ]
        },
        {
            id:28,
            name:"附属教育机构",
            open:"closed",
            status:false,
            children:[
                {
                    id:29,
                    name:"深圳技术大学幼儿园",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:30,
                    name:"深圳技术大学附属中学",
                    open:"",
                    status:false,
                    children:null,
                }
            ]
        },
        {
            id:31,
            name:"教学单位",
            open:"closed",
            status:false,
            children:[
                {
                    id:32,
                    name:"应用高等教育研究院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:33,
                    name:"中德智能制造学院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:34,
                    name:"药学院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:35,
                    name:"质量和标准学院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:36,
                    name:"创意设计学院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:37,
                    name:"集成电路与光电芯片学院",
                    open:"closed",
                    status:false,
                    children:[
                        {
                            id:38,
                            name:"集成光电子工程中心（挂靠集成电路）",
                            open:"",
                            status:false,
                            children:null,
                        }
                    ]
                },
                {
                    id:39,
                    name:"商学院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:40,
                    name:"未来技术学院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:41,
                    name:"健康与环境工程学院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:42,
                    name:"大数据与互联网学院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:43,
                    name:"外国语学院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:44,
                    name:"新材料与新能源学院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:45,
                    name:"工程物理学院",
                    open:"",
                    status:false,
                    children:[
                        {
                            id:46,
                            name:"超强激光应用技术研究中心",
                            open:"",
                            status:false,
                            children:null,
                        }
                    ]
                },
                {
                    id:47,
                    name:"研究生院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:48,
                    name:"音乐学院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:49,
                    name:"体育与艺术学院",
                    open:"closed",
                    status:false,
                    children:[
                        {
                            id:50,
                            name:"体育场馆管理中心",
                            open:"",
                            status:false,
                            children:null,
                        }
                    ]
                },
                {
                    id:51,
                    name:"马克思主义学院（人文社科学院）",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:52,
                    name:"口腔学院",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:53,
                    name:"城市交通与物流学院",
                    open:"",
                    status:false,
                    children:null,
                }
            ]
        },
        {
            id:54,
            name:"群团组织",
            open:"closed",
            status:false,
            children:[
                {
                    id:55,
                    name:"校团委",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:56,
                    name:"校工会",
                    open:"",
                    status:false,
                    children:null,
                }
            ]
        },
        {
            id:57,
            name:"其他直属机构",
            open:"closed",
            status:false,
            children:[
                {
                    id:58,
                    name:"采购与招投标管理中心",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:59,
                    name:"学生就业指导中心",
                    open:"",
                    status:false,
                    children:null,
                }
            ]
        },
        {
            id:60,
            name:"其他",
            open:"",
            status:false,
            children:null,
        },
        {
            id:61,
            name:"校领导",
            open:"",
            status:false,
            children:null,
        },
        {
            id:62,
            name:"教辅单位",
            open:"closed",
            status:false,
            children:[
                {
                    id:63,
                    name:"图书馆",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:64,
                    name:"信息中心",
                    open:"",
                    status:false,
                    children:null,
                },
                {
                    id:65,
                    name:"教学质量督导室",
                    open:"",
                    status:false,
                    children:null,
                }
            ]
        }
    ]
  }]);

// 更新每个节点的open状态
const updateNodeOpenStatus = (data: TreeNode[],targetId: number): void => {
  //如果是当前节点
  data.forEach(item => {
    if(item.id === targetId){
        item.open = item.open === "" ?  "" : item.open === "open" ? "closed" : "open"; 
        return;
    }
    // 如果存在子节点
    if(item.children){
        updateNodeOpenStatus(item.children,targetId);
    }
  })
};

// 更新每个子节点的status属性
const updateNodeSonStatus = (data: TreeNode[], targetId: number):void => {
  //如果是当前节点
  data.forEach(item => {
    if(item.id === targetId){
      if(item.children) {
        item.children.forEach(e => {
            e.status = !e.status;
            return;
        })
      }
    }
    // 如果存在子节点
    if(item.children){
        updateNodeSonStatus(item.children,targetId);
    }
  })
};


export default function useItemList() {
  return {
    AllItemList,
    updateNodeOpenStatus,
    updateNodeSonStatus,
  };
}